#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "twenty"
name = "Twenty CRM"
description.en = "The #1 Open-Source CRM."
description.fr = "Le CRM Open-Source N°1."

version = "1.18.0~ynh1"

maintainers = ["YunoHost-Apps"]

[upstream]
license = "AGPL-3.0"
website = "https://twenty.com"
code = "https://github.com/twentyhq/twenty"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "500M"
ram.build = "128M"
ram.runtime = "2048M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    # No tarball required for this docker-wrapper app, we fetch docker-compose via our templates.
    # We still define an empty source so it passes lint, or we can use the docker-compose repo as source.
    [resources.sources.main]
    url = "https://github.com/twentyhq/twenty/archive/refs/tags/v1.18.0.tar.gz"
    sha256 = "55757a50d5c7e553e4d905ffa2cb9915a63565e5416af4f94b4df19690c80ce8"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    [resources.install_dir]
    [resources.data_dir]
    [resources.permissions]
    main.url = "/"
    
    [resources.ports]
    main.default = 3000
    
    [resources.apt]
    packages = ["docker.io", "docker-compose"]
