#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Removing system configurations..."

# Stop and remove Docker containers AND their anonymous volumes
pushd "$install_dir" > /dev/null 2>&1 || true
    docker-compose --project-name "$app" down --volumes --remove-orphans 2>/dev/null || true
popd > /dev/null 2>&1 || true

# Free space!
docker image prune -f --filter "label=com.docker.compose.project=$app" 2>/dev/null || true

yunohost service remove "$app"
ynh_config_remove_systemd
ynh_config_remove_nginx

ynh_safe_rm "/var/log/$app"

ynh_script_progression "Removal of $app completed"
